platform :ios, '13.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def default_pods
  pod 'goSellSDK', :path => '../'
end

target 'goSellSDKExample' do
    default_pods
end

target 'GoSellAppClip' do
  default_pods
end
