platform :ios, '13.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def default_pods
  pod 'goSellSDK', :path => '../'
end

target 'goSellSDKExample' do
    default_pods
end

target 'GoSellAppClip' do
  default_pods
end



post_install do |installer|
	
	installer.pods_project.targets.each do |target|
		
        target.build_configurations.each do |config|
            
            if config.name.include?("Debug")
                
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
                
            end
            
        end
        
    end
    
end
