platform :ios, '11.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'goSellSDKExample' do
    
    pod 'Crashlytics'
    pod 'Fabric'
    
    pod 'goSellSDK', :path => '../'
	pod 'goSellSDK/ErrorReporting', :path => '../'

end

post_install do |installer|
	
	installer.pods_project.targets.each do |target|
		
        target.build_configurations.each do |config|
            
            if config.name.include?("Debug")
                
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
                
            end
            
        end
        
    end
    
end
